export const data = [
  {
    displayName: 'Samyaza',
    value: 'samyaza',
    title: 'Angel of Pride',
    description: 'Samyaza é o líder dos Watchers. Foi o primeiro a receber seu nome',
  },
  { displayName: 'Azazel', value: 'azazel' },
  { displayName: 'Kokabiel', value: 'kokabiel' },
  { displayName: 'Rahab', value: 'rahab' },
  { displayName: 'Suphlatus', value: 'suphlatus' },
  { displayName: 'Gadreel', value: 'gadreel' },
  { displayName: 'Sariel', value: 'sariel' },
  { displayName: 'Ananiel', value: 'ananiel' },
  { displayName: 'Turiel', value: 'turiel' },
  { displayName: 'Sathariel', value: 'sathariel' },
  { displayName: 'Baraqiel', value: 'baraqiel' },
  { displayName: 'Af', value: 'af' },
  { displayName: 'Bezaliel', value: 'bezaliel' },
  { displayName: 'Penemue', value: 'penemue' },
  { displayName: 'Chazaqiel', value: 'chazaqiel' },
  { displayName: 'Tamiel', value: 'tamiel' },
  { displayName: 'Samshiel', value: 'samshiel' },
  { displayName: 'Zaqiel', value: 'zaqiel' },
  { displayName: 'Asbeel', value: 'asbeel' },
  { displayName: 'Armaros', value: 'armaros' },
];
